language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t kamiel9/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true kamiel9/docker-react npm run test
